/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrashRouteImport } from './routes/app.trash'
import { Route as AppTagsRouteImport } from './routes/app.tags'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMindmapRouteImport } from './routes/app.mindmap'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppNotesIndexRouteImport } from './routes/app.notes.index'
import { Route as AppProfileEditRouteImport } from './routes/app.profile.edit'
import { Route as AppNotesNewRouteImport } from './routes/app.notes.new'
import { Route as AppNotesIdRouteImport } from './routes/app.notes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/app/trash',
  path: '/app/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/app/tags',
  path: '/app/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMindmapRoute = AppMindmapRouteImport.update({
  id: '/app/mindmap',
  path: '/app/mindmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/app/help',
  path: '/app/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/app/favorites',
  path: '/app/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/app/activity',
  path: '/app/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/app/notes/',
  path: '/app/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/app/notes/new',
  path: '/app/notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesIdRoute = AppNotesIdRouteImport.update({
  id: '/app/notes/$id',
  path: '/app/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/help': typeof AppHelpRoute
  '/app/mindmap': typeof AppMindmapRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/trash': typeof AppTrashRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/help': typeof AppHelpRoute
  '/app/mindmap': typeof AppMindmapRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/trash': typeof AppTrashRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/help': typeof AppHelpRoute
  '/app/mindmap': typeof AppMindmapRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/trash': typeof AppTrashRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/dashboard'
    | '/app/favorites'
    | '/app/help'
    | '/app/mindmap'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tags'
    | '/app/trash'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/profile/edit'
    | '/app/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/dashboard'
    | '/app/favorites'
    | '/app/help'
    | '/app/mindmap'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tags'
    | '/app/trash'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/profile/edit'
    | '/app/notes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/dashboard'
    | '/app/favorites'
    | '/app/help'
    | '/app/mindmap'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tags'
    | '/app/trash'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/profile/edit'
    | '/app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppMindmapRoute: typeof AppMindmapRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppTrashRoute: typeof AppTrashRoute
  AppNotesIdRoute: typeof AppNotesIdRoute
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trash': {
      id: '/app/trash'
      path: '/app/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tags': {
      id: '/app/tags'
      path: '/app/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mindmap': {
      id: '/app/mindmap'
      path: '/app/mindmap'
      fullPath: '/app/mindmap'
      preLoaderRoute: typeof AppMindmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/help': {
      id: '/app/help'
      path: '/app/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/app/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/app/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/app/notes'
      fullPath: '/app/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/notes/new': {
      id: '/app/notes/new'
      path: '/app/notes/new'
      fullPath: '/app/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notes/$id': {
      id: '/app/notes/$id'
      path: '/app/notes/$id'
      fullPath: '/app/notes/$id'
      preLoaderRoute: typeof AppNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHelpRoute: AppHelpRoute,
  AppMindmapRoute: AppMindmapRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
  AppTrashRoute: AppTrashRoute,
  AppNotesIdRoute: AppNotesIdRoute,
  AppNotesNewRoute: AppNotesNewRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
